### PR TITLE
split code into multiple files to make it easier to contribute

### PR DESCRIPTION
**Pull request by timaschew**
contribution could be maybe an alternative parser besides ABC

### CODE REVIEW

**Comment by timaschew** [comment]
use now: 

```
new musical.Instrument('piano');
```
but the __musical__ can be changed to anything via `browserify -s NAME`

**Comment by timaschew** [comment]
I fixed the test now, any feedback?
BTW: I started another branch in my fork where I extract the ABC parser from the Instrument "class". 
I want to provide another alternative syntax to write notes.

**Comment by davidbau** [comment]
Hi Tim - don't know how i missed this pull request.  Looks good to me, and merging.

**Comment by timaschew** [comment]
Hi David,
I'm glad to see the merge :)

In the meantime I continued work in [my fork of musical.js](https://github.com/timaschew/musical.js/commits/split-parser).
I tried to split the parser from the Instrument to make it easier to provide some alternatives to abc.
But for now I stick to abc, after some time the format convinced me :smile: 

I also tried to get notified via `noteon` and `noteoff` for rests. My solution is a little bit dirty ,because I changed the internal rest into a real note with a pitch which is so high, that it can't be played (or listened) :smirk_cat: 
Maybe you have a better idea or solution?

**Pull request merged**
